### ISSUE TITLE
Unable to use integration

### ISSUE THREAD

**Issue by LuisDiazUgena** [chomupashchuk/ariston-remotethermo-home-assistant-v2#65]
Hi,

I have setted up the integration for the Genus One Wifi and it's reporting values, but, it's not able to change the values using the services available.

Using the provided example on developer tools i wrote this piece of code:

```
service: ariston.set_data
data:
  entity_id: climate.ariston_zone1
  ch_comfort_temperature_zone1: 23
  ch_economy_temperature_zone1: 21
```

After using this, it's sais ok on the 'call service' button (bottom right corner):

![image](https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/assets/6543254/70acfa46-6f5b-4a8e-a21c-504028f16625)

it seems that it's not able to change the property properly on server side?

For further info, I have a wireless sensor configured on manual. I have found that it doesn't work either on time based or off. I can change it using the Ariston app or the website.

Anything else I could provide to help with this?
